### ISSUE TITLE
Cannot change listening port?

### ISSUE THREAD

**Issue by minhducsun2002** [vnma0/kon#10]
```
> kon@1.0.0 start /tmp/kon
> node src/server.js

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::30000
```

No method to change listening port has been documented.

**Comment by dungwinux** [comment]
This must be the `on-death` package, I'll try working on it.

**Comment by minhducsun2002** [comment]
It has nothing to do with `death` judging from the execution flow - binding to port already failed before the `ON_DEATH` call gets the chance to be invoked.

It fails due to `app.listen` throws, not `ON_DEATH` throws.

**Comment by dungwinux** [comment]
Occasionally, `on-death` will failed to trigger code run after executing, thus the port is still occupied until you terminate the program.

**Comment by minhducsun2002** [comment]
Why don't you use `process.on('SIGTERM', () => process.exit())` or something like that? It is much more reliable - we call native things directly.

**Comment by dungwinux** [comment]
Don't say such thing unless you've tried it on Windows. It won't work correctly.

**Comment by minhducsun2002** [comment]
Okay, I'mma do more testing.

`SIGTERM` doesn't work on Windows, but so does `SIGINT`? To my understanding, you don't fire up the terminal in raw mode?

**Comment by dungwinux** [comment]
Issue invalid due to mechanism change.
